CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Phone VARCHAR(20),
    City VARCHAR(50),
    State VARCHAR(50),
    PhoneBrand VARCHAR(50),
    OperatingSystem VARCHAR(20)
);
SELECT * FROM customers;


CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Category VARCHAR(50),
    Price DECIMAL(10,2),
    Rating DECIMAL(2,1),
    NumberOfPepopleRated INT
);
SELECT * FROM products;




CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    ProductID INT,
    Quantity INT,
    OrderDate TIMESTAMP,
    DeliveryDate TIMESTAMP,
    DeliveryStatus VARCHAR(20),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
SELECT * FROM orders;


-- total revenue
SELECT SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
  ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered';  


-- total number of orders
SELECT COUNT(DISTINCT orderid) AS total_order	   
FROM orders o
JOIN products p
  ON o.productid = p.productid; 

-- average order value
SELECT SUM(p.price * o.quantity)
               /
	   COUNT(DISTINCT orderid) AS AOV	   
FROM orders o
JOIN products p
  ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered'; 


-- revenue generated by each category.
SELECT p.category,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
  ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY p.category
ORDER BY total_revenue DESC;


-- top 5 products by revenue.
SELECT p.productname,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
  ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY p.productname
ORDER BY total_revenue DESC
LIMIT 5;


-- Find bottom 5 products by revenue.
SELECT p.productname,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
  ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY p.productname
ORDER BY total_revenue 
LIMIT 5;


-- Calculate the percentage contribution of each category to total revenue.
SELECT p.category,
       SUM(p.price * o.quantity) AS total_revenue,
	   ROUND(
	         SUM(p.price * o.quantity) * 100
	             /
	        ( 
			  SELECT SUM(p1.price * o1.quantity)
              FROM orders o1
              JOIN products p1
                 ON o1.productid = p1.productid
              WHERE o1.deliverystatus = 'Delivered'
			 ),
			  2
			 ) AS percentage_contribution
FROM orders o
JOIN products p
  ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY p.category
ORDER BY total_revenue DESC;


OR 

-- Calculate the percentage contribution of each category to total revenue.
WITH category_revenue AS (
                         SELECT p.category,
                               SUM(p.price * o.quantity) AS total_revenue
                         FROM orders o
                         JOIN products p
                              ON o.productid = p.productid
                         WHERE o.deliverystatus = 'Delivered'
                         GROUP BY p.category
                         ORDER BY total_revenue DESC)

SELECT category,
       total_revenue,
	   total_revenue * 100
	         /
	   SUM(total_revenue) OVER() AS percentage_contribution
FROM category_revenue;	   


-- Customer Analysis
-- total number of customers.
SELECT COUNT(DISTINCT customerid)
FROM customers;


-- top 10 customers by spending.
SELECT CONCAT_WS(' ',firstname,lastname) AS fullname,
       SUM(p.price * o.quantity) AS total_spend
FROM orders o
JOIN products p
  ON o.productid = p.productid
JOIN customers c 
  ON o.customerid = c.customerid
WHERE o.deliverystatus = 'Delivered'  
GROUP BY  c.customerid, c.firstname, c.lastname
ORDER BY total_spend DESC
LIMIT 10;

		  
-- customer count by state.
SELECT state,
       COUNT(customerid) AS total_customer     
FROM customers
GROUP BY state
ORDER BY total_customer DESC;


-- customer count by city.
SELECT city,
       COUNT(customerid) AS total_customer     
FROM customers 
GROUP BY city
ORDER BY total_customer DESC;


-- Revenue by State
SELECT
    c.state,
    SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN customers c
    ON o.customerid = c.customerid
JOIN products p
    ON o.productid = p.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY c.state
ORDER BY total_revenue DESC;


-- revenue generated by Android vs iOS users.
SELECT c.operatingsystem,
       SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
   ON p.productid = o.productid
JOIN customers c
   ON c.customerid = o.customerid
WHERE o.deliverystatus = 'Delivered'   
GROUP BY c.operatingsystem;



-- repeat customers (customers with more than 1 order).
SELECT c.customerid,
       CONCAT_WS(' ', c.firstname, c.lastname) AS fullname,
	   COUNT(o.orderid) AS total_order
FROM orders o
JOIN customers c
  ON c.customerid = o.customerid
GROUP BY c.customerid,c.firstname,c.lastname
HAVING COUNT(o.orderid) > 1
ORDER BY total_order DESC;  
 

-- Product Analysis
-- total revenue generated by each product.
SELECT p.productid,
       p.productname,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
  ON p.productid = o.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY p.productid,p.productname
ORDER BY total_revenue DESC;
  

-- highest-rated products.	   
SELECT *
FROM products
ORDER BY rating DESC
LIMIT 10;


-- products whose revenue is above the average product revenue.
WITH product_revenue AS (
                   SELECT p.productid,
                          p.productname,
	                      SUM(p.price * o.quantity) AS total_revenue
                   FROM orders o
                   JOIN products p 
                     ON o.productid = p.productid
				   WHERE o.deliverystatus = 'Delivered' 
                   GROUP BY p.productid,p.productname
)

SELECT * FROM product_revenue 
WHERE total_revenue > (
                      SELECT AVG(total_revenue)
					  FROM product_revenue
);


-- Rank all products based on revenue.
WITH product_revenue AS (
                    SELECT p.productid,
                           p.productname,
	                       SUM(p.price * o.quantity) AS total_revenue
                    FROM orders o
                    JOIN products p 
                      ON o.productid = p.productid
					WHERE o.deliverystatus = 'Delivered'  
                    GROUP BY p.productid,p.productname)
 
SELECT DENSE_RANK() OVER(ORDER BY total_revenue DESC) AS revenue_rank,
       *
FROM product_revenue;


-- top 3 revenue-generating products within each category.
WITH product_revenue_category_vise AS (
                    SELECT 
					       p.productid,
                           p.productname,
						   p.category,
	                       SUM(p.price * o.quantity) AS total_revenue
                    FROM orders o
                    JOIN products p 
                      ON o.productid = p.productid
					WHERE o.deliverystatus = 'Delivered'  
                    GROUP BY p.productid,p.productname,p.category
					)

SELECT * 
FROM (
       SELECT 
	         DENSE_RANK() OVER(
                   PARTITION BY category 
				   ORDER BY total_revenue DESC
	         ) AS revenue_ranking_by_category,
	          productid,
              productname,
              category,
              total_revenue          
       FROM product_revenue_category_vise
) t
WHERE revenue_ranking_by_category <= 3;
   
				 
-- monthly revenue trends.

SELECT EXTRACT('Month' FROM o.orderdate) AS month,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
   ON p.productid = o.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY EXTRACT('Month' FROM o.orderdate)
ORDER BY month;

-- OR 
SELECT DATE_TRUNC('Month',o.orderdate) AS month,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
   ON p.productid = o.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY DATE_TRUNC('Month',o.orderdate)
ORDER BY month;



-- the busiest month based on number of orders.
SELECT TO_CHAR(orderdate,'YYYY-MM') AS month,
       COUNT(orderid) AS total_orders
FROM orders
GROUP BY TO_CHAR(orderdate,'YYYY-MM')
ORDER BY total_orders DESC
LIMIT 1;


-- busiest day of the week.
SELECT TO_CHAR(orderdate,'FMDay') AS weekday_num,
       COUNT(orderid) AS total_orders
FROM orders
GROUP BY TO_CHAR(orderdate,'FMDay')
ORDER BY total_orders DESC
LIMIT 1;

-- OR
SELECT EXTRACT(DOW FROM orderdate) AS weekday_num,
       COUNT(orderid) AS total_orders
FROM orders
GROUP BY EXTRACT(DOW FROM orderdate)
ORDER BY total_orders DESC
LIMIT 1;


-- Find the purchase hour generating the highest revenue.
SELECT EXTRACT(Hour FROM o.orderdate) AS purchase_hour,
       SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
   ON p.productid = o.productid
WHERE o.deliverystatus = 'Delivered'
GROUP BY EXTRACT(Hour FROM o.orderdate)
ORDER BY total_revenue DESC
LIMIT 1;



-- average delivery time.
SELECT 
	 AVG(DeliveryDate - OrderDate) AS avg_deleivery_time
FROM orders
WHERE deliverystatus = 'Delivered';


-- cancellation rate.
SELECT 
      ROUND(
	  100 * COUNT(orderid)
	  /
     (SELECT
       COUNT(orderid) total_orders
      FROM orders) 
	  ,2
	  ) AS cancellation_rate
FROM orders
WHERE deliverystatus = 'Cancelled';
	   
	 

-- revenue lost due to cancelled orders.
SELECT 
       SUM(o1.quantity * p1.price) AS revenue_of_cancel_order
FROM orders o1
JOIN products p1
  ON o1.productid = p1.productid
WHERE o1.deliverystatus = 'Cancelled';
